name: 'command'
description: 'Run zola check'
author: 'Kenzi Connor'
inputs:
  content:
    description: Directory to run zola build in - root of the content site
    required: false
    default: '.'
    type: string
  flags:
    description: flags for check and build, eg --drafts --base-url
    required: false
    default: ''
    type: string
runs:
  using: 'composite'
  steps:
    - name: Output variables
      shell: bash
      run:  echo '${{ toJSON(inputs) }}'
    - name: zola check
      if: inputs.command == 'check'
      shell: bash
      run: zola --root ${{ inputs.content }} check ${{ inputs.flags }}