name: Zola CLI
description: Run zola commands after installing. Use @build or @check to run actual commands
author: Kenzi Connor
branding:
  icon: align-justify
  color: purple
runs:
  using: composite
  steps:
    - name: output variables
      shell: bash
      run: echo '${{toJSON(inputs)}}'
    - uses: knzai/zola-cli@install