#Still depends on triggering default gh deploy actions 
name: Zola CLI
description: Run zola build/check with idempotent zola install
author: Kenzi Connor
branding:
  icon: book
  color: green
inputs:
  command:
    description: specify zola command, otherwise defaults to both. Install is idempotent and always called
    required: false
    default: 'both'
    type: choice
    options:
      - install
      - check
      - build
      - both
  root:
    description: Directory to use as root of project 
    required: false
    default: '.'
    type: string
  config:
    description: Path to a config file other than config.toml in the root of project
    required: false
    default: 'config.toml'
    type: string
  base-url:
    description: Force the base URL to be that value (defaults to the one in config)
    required: false
    default: ''
    type: string
  drafts:
    description: Include drafts when loading the site
    required: false
    default: false
    type: boolean
  output-dir:
    description: Outputs the generated site in the given path (by default 'public' dir in project root)
    required: false
    default: 'public'
    type: string
  force:
    description: Force building the site even if output directory is non-empty
    required: false
    default: false
    type: boolean

runs:
  using: composite
  steps:
    - name: output variables
      shell: bash
      run: echo '${{toJSON(inputs)}}'
    - name: build flags
      shell: bash
      run: |
        echo "base_command=zola -r ${{inputs.root}} -c ${{inputs.config}}" >> $GITHUB_ENV
        if ${{ inputs.drafts }}; then
          echo "drafts_flag=--draft" >> $GITHUB_ENV
        fi
        build_flags='-o ${{inputs.output-dir}}'
        if ${{inputs.force}}; then
          build_flags="-o $build_flags --force"
        fi
        echo "build_flags=$build_flags" >> $GITHUB_ENV
    - uses: actions/checkout@master
      with:
        path: zola-cli
    - uses: ./zola-cli/install
    - name: zola check
      if: inputs.command == 'check' || inputs.command == 'both'
      shell: bash
      run: $base_command check $drafts_flag
    - name: zola build
      if: inputs.command == 'build' || inputs.command == 'both'
      shell: bash
      run: $base_command build $drafts_flag $build_flags
