name: 'install'
description: 'Install zola'
author: 'Kenzi Connor'
runs:
  using: 'composite'
  steps:
    - name: Install zola
      if:  true && ! env.zola_installed
      uses: taiki-e/install-action@zola
    - name: store install state of zola for idempotency
      shell: bash
      run: |
        if command -v zola > /dev/null 2>&1; then
            echo "zola_installed=true" >> $GITHUB_ENV
        fi